### ISSUE TITLE
Create Google Analytics integration for tracking all site activity

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/school-rankings#47]
Create custom events in Google Analytics for tracking all interesting site activity.

### Custom hit-level dimensions for ranking pool / "what is being ranked" events:
- [x] `dimension1`: "context"
      ("school" or "school corporation")
- [x] `dimension2`: "geographic area"
      (e.g. Brown County, IN)
- [x] `dimension3`: "school type"
      A slash-delimited alphabetized list of all selected school types (e.g. public; private / public; charter / private / public)
- [x] `dimension4`: "grade levels"
      (described below)

### Custom hit-level dimensions / metrics for ranking criteria / "how it's being ranked" events:
One per criterion
- [x] "metric" (Google Analytics dimension)
     - A string representing a metric and its entire ancestor path
     - If 150-byte limit is exceeded, a series of progressively severe abbreviations takes place
     - If limit is still exceeded, the first and last metrics are preserved and the largest middle metrics are trimmed
- [x] "weight" (Google Analytics metric)

### Note
Because "what gets ranked" and "how it gets ranked" are going to be recorded as separate events with different sets of dimensions, these can only be reported on independently of another. If a report is requested that shows correlations between "what" and "how" dimensions, that could be made manually based on data recorded in the School Rankings database.

### Track when a link to a school/district in the results is clicked
Research needed

### Tracking selected grade levels
 - Recorded as a range of `"$lowestGrade-$highestGrade"`
 - This would ignore skipped grades in the middle (e.g. 8, 9, 11, 12), but that's unlikely to happen and shouldn't matter.
 - Use preschool, pre-kindergarten, and kindergarten as standalone grade levels
 - Use grades 1, 6, and 9 as the possible low ends of grade ranges
 - Use grades 5, 8, and 12 as the possible high ends of grade ranges
 - Pre-s, pre-k, and kindergarten can also be low or high ends of grade ranges
 - Examples (selected => reported):
    - k => "kindergarten"
    - pre-s, pre-k, k => "preschool - kindergarten"
    - pre-k, k, 1 => "pre-kindergarten - grade 5"
    - 1, 2, 3, 4, 5 => "grade 1 - grade 5"
    - 4, 5, 6, 7 => "grade 1 - grade 8"
 - Rationale: This doesn't match [the myriad ways](https://en.wikipedia.org/wiki/K–12#/media/File:US-K12.gif) grades are can be grouped into elementary / middle / (junior and/or senior) high, but it seems like the best chance at generating the smallest number of useful strings to describe grade selections.

### Multiple geographies
Unanswered question: How do we save geography information to custom dimensions when multiple geographies are allowed? Maybe supporting multiple geographies is never going to actually be implemented, as it may be determined that allowing the user to select a single state, county, MSA, city, or range should be sufficient for all users.
